version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-api
    ports:
      - "8000:8000"
  
  frontend:
    image: python:3.10
    container_name: gradio-ui
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "7860:7860"
    command: bash -c "pip install gradio requests && python frontend.py"
    depends_on:
      - api
