version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-api
    ports:
      - "8000:8000"
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gradio-ui
    ports:
      - "7860:7860"
    depends_on:
      - api
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
