version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gradio-ui
    ports:
      - "7860:7860"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
